# Generated by Django 4.2.2 on 2023-06-15 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='data_joined',
            new_name='date_joined',
        ),
    ]
